apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres-ha.name }}
type: Opaque
data:
  username: {{ .Values.postgres-ha.username }}
  password: {{ .Values.postgres-ha.password }}
  database: {{ .Values.postgres-ha.database }}